### PR TITLE
update Dockerfile for API 25

### PR DESCRIPTION
**Pull request by mockturtl**

### CODE REVIEW

**Comment by viktorbenei** [comment]
awesome, thank you very much!

just one more thing: could you please add this to the `CHANGELOG` too?

**Comment by viktorbenei** [comment]
Sorry, I'll do that ;)

Thanks again!

**Comment by mockturtl** [comment]
Thank you!  :heart:  bitrise!

**Comment by viktorbenei** [comment]
Thanks, we ❤️ you too! ;)

**Pull request merged**
