### PR TITLE
preinstalled packages cleanup

### PR DESCRIPTION
**Pull request by viktorbenei**

### CODE REVIEW

**Comment by julo15** [comment]
I'm wondering about the reason for aggressively cleaning up these older build tools versions. I have an app that uses version `25.0.1` of the build tools, and just had my workflows fail because the version is no longer installed on the bitrise docker image.

This is an annoyance, as I'll need to either bump the app's build tools version whenever this cleanup is done, or add a line to my workflow to ensure the version I use is installed.

I can understanding wanting to remove very old build tools version, but I feel like using `25.0.1` shouldn't cause a build failure since the version is pretty current.

**Comment by viktorbenei** [comment]
@julo15 : first of all sorry for the inconvenience, we don't plan to do this kind of cleanup often. Actually this was the first time we removed a package (other than when a package disappeared from the available android packages list) since the start of our new Docker based Linux infra (a bit more than a year ago).

> I'm wondering about the reason for aggressively cleaning up these older build tools versions.

Reason (from https://developer.android.com/studio/releases/build-tools.html):

> You should always keep your Build Tools component updated by downloading the latest version using the Android SDK Manager. By default, the Android SDK uses the most recent downloaded version of the Build Tools. If your projects depend on older versions of the Build Tools, the SDK Manager allows you to download and maintain separate versions of the tools for use with those projects.

We'll release a new step today which will be able to auto detect which basic android packages your project requires and auto install them, including the build tools version package, that should make this process easier in the future. But again, we don't plan to remove old packages in the near future, and we'll definitely prepare for this better the next time.

Again, sorry for the inconvenience and let us know if we can help with anything!

**Comment by julo15** [comment]
@viktorbenei Sweet, having a step to detect those things sounds really great. Is this a separate step we would need to add or something that will run automatically with the common Android bitrise setup?

And I agree with keeping build tools up to date - I was more worried about the problem of needing to frequently deal with Bitrise build failures due to this. But it sounds like that won't be the case :).

Thanks for the explanation and follow up!

**Comment by viktorbenei** [comment]
> But it sounds like that won't be the case :).

It definitely won't be - although I can't guarantee it, due to various constraints, but I wouldn't be surprised if the next build tools cleanup would be next year ;)

> Sweet, having a step to detect those things sounds really great. Is this a separate step we would need to add or something that will run automatically with the common Android bitrise setup?

If you register a new Android project this step is now added to the base config automatically, for existing projects you have to add it. The step was released earlier today - related announcement discussion: https://discuss.bitrise.io/t/android-automatic-dependency-installer-e-g-build-tools-step-install-missing-android-tools/316

**Pull request merged**
