### PR TITLE
Add Mono

### PR DESCRIPTION
**Pull request by Redth**
This adds Mono from the official mono debian package source (so, up to date, stable releases).

### CODE REVIEW

**Comment by viktorbenei** [comment]
Thanks for the Pull Request! We'll discuss whether this should be part of the Android docker image. In any case, you can of course do this in a Script step to have mono installed.

**Comment by viktorbenei** [comment]
Just a question: why do you think this should be pre-installed in the Android image?

**Comment by viktorbenei** [comment]
Just a note: Please re-create this Pull Request in the [bitrise-base](https://github.com/bitrise-docker/bitrise-base) docker image, so that it can be used for non Android projects too.

And a question: should this be added to the OS X stacks too? Probably it can be installed from `brew` [there](https://github.com/bitrise-io/osx-box-bootstrap). We have to unify this across the stacks, to allow Steps targeting Mono regardless of the stack/OS.

**Comment by viktorbenei** [comment]
What do you think about the OSX stack? Also, if you don't have time to recreate the PR for the base Docker image just let us know and we'll try to schedule it asap - once we figure out a way for the osx stack

**Comment by viktorbenei** [comment]
Just a question : do you have experience with Mono installed from brew? If that works correctly then we can preinstall mono on the new OSX stacks, and install it on the fly, when required, on older osx stacks.

**Comment by Redth** [comment]
Ahh yeah sorry I forgot about recreating the PR, and unfortunately can't do much with that before Evolve.  I think it'd be great to have on the OSX stack too.  Honestly I think having the ability to make integrations in C# for any image is ideal.  You could install via `brew` on OSX though, definitely!

**Comment by viktorbenei** [comment]
OS X note: we should skip installing & using `brew` based mono, and we should rather use the one which comes with Xamarin

**Comment by viktorbenei** [comment]
I think it's time to close this PR, as it seems the better choice long term would be to install .Net Core instead.

What do you think @Redth ?

P.S.: sorry that this took so long, we were just not really keen in adding a tool which we thought will be replaced with another one in the near future. We never forgot about this, just could not decide yet.

**Comment by viktorbenei** [comment]
Note: .Net Core pre-install was just accepted into the Xamarin stacks (https://github.com/bitrise-io/osx-box-bootstrap/pull/41)

**Comment by Redth** [comment]
Yeah this is probably ok long term.  The main reason I can think of you'd want mono instead is to build Mac/iOS/Android stuff, which it seems you have images specifically with it for Xamarin already.  Xamarin will require mono for the foreseeable future.

**Comment by viktorbenei** [comment]
> The main reason I can think of you'd want mono instead is to build Mac/iOS/Android stuff, which it seems you have images specifically with it for Xamarin already. 

Indeed, additionally Xamarin probably won't be available for Linux, at least from what we can see it seems so ;)

> Xamarin will require mono for the foreseeable future.

And we'll keep supporting it on MacOS of course, as we do clean Xamarin installs, so as long as the Xamarin installer installs mono it'll be installed there (we try to be as careful as possible with minimizing any custom magic or manual setup/steps, and instead use the official tools & installers).

**Comment by viktorbenei** [comment]
Ohh, and of course, thanks @Redth for the PR and for all the infos and help! We really appreciate it!

**Pull request closed without merging**
